# Generated by Django 5.2.6 on 2025-10-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0005_attendance_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.ManyToManyField(blank=True, related_name='student_attendances', to='stud.attendance'),
        ),
        migrations.AddField(
            model_name='student',
            name='results',
            field=models.ManyToManyField(blank=True, related_name='student_results', to='stud.results'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='stud.student'),
        ),
        migrations.AlterField(
            model_name='results',
            name='grade',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='results',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_records', to='stud.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
